sonar.projectKey=loliman_shortbox-react
sonar.organization=loliman
sonar.host.url=https://sonarcloud.io
sonar.newCode.referenceBranch=main
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/mock/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
